name: Test progenitor-generated client
on:
  pull_request:
jobs:
  run-example:
    name: "Test example on progenitor-generated client"
    runs-on: ubuntu-latest
    timeout-minutes: 5 
    steps:
      - uses: actions/checkout@v4
      - name: Build and run
        run: |
          cargo install cargo-progenitor --git https://github.com/PolyProgrammist/progenitor --branch patch_rustfmt
          ./test.sh
