name: Regenerate client and create pull request if it's updated

permissions:
  pull-requests: write
  contents: write

on:
  schedule:
    - cron: '0 1 * * *'  # Runs daily at 1 hour after midnight
  workflow_dispatch:

jobs:
  regenerate-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and run
        run: |
          cargo install cargo-progenitor --git https://github.com/PolyProgrammist/progenitor --branch patch_rustfmt
          ./generate.sh
          if git diff --quiet; then
            echo "No changes, exiting."
            exit 0
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: regenerate client
          token: ${{ secrets.RELEAZE_PLZ_GITHUB_TOKEN }}